spring:
  neo4j:
    uri: bolt://localhost:57687
    authentication:
      username: neo4j
      password: 1234568aA!
logging:
  level:
    org.neo4j.driver: DEBUG   # 若需调试可开
    org.springframework.data.neo4j: DEBUG
